import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
INJECT_LINE = '<link rel="stylesheet" href="custom_theme.css">'

httrack_patterns = [
    re.compile(r'<!--[^>]*HTTrack[^>]*-->', re.IGNORECASE|re.DOTALL),
    re.compile(r'<!--\s*Mirrored from[\s\S]*?-->', re.IGNORECASE),
    re.compile(r'<!--\s*Added by HTTrack[\s\S]*?-->', re.IGNORECASE),
    re.compile(r'<!--\s*Generated by HTTrack[\s\S]*?-->', re.IGNORECASE),
]

modified = []
for dirpath, dirnames, filenames in os.walk(ROOT):
    for fn in filenames:
        if not fn.lower().endswith('.html'):
            continue
        path = os.path.join(dirpath, fn)
        try:
            with open(path, 'r', encoding='utf-8') as f:
                content = f.read()
        except UnicodeDecodeError:
            with open(path, 'r', encoding='latin-1') as f:
                content = f.read()

        orig = content
        # Remove HTTrack / Mirrored comments
        for pat in httrack_patterns:
            content = pat.sub('', content)

        # Only inject if not already present
        if INJECT_LINE not in content:
            head_close = content.lower().rfind('</head>')
            if head_close != -1:
                # find the real index in original case-sensitive content
                match = re.search(r'</head>', content, re.IGNORECASE)
                if match:
                    idx = match.start()
                    content = content[:idx] + INJECT_LINE + '\n' + content[idx:]

        if content != orig:
            try:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(content)
                modified.append(path)
            except Exception as e:
                print(f'Failed to write {path}: {e}')

print(f"Modified {len(modified)} HTML files")
for p in modified:
    print(p)
