import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

# We'll compute a per-file relative path to the project's `custom_theme.css` so
# HTML files in nested folders get the correct relative href (or use a simple
# relative path when the file is in the project root).

CSS_TARGET = os.path.join(ROOT, 'custom_theme.css')

def make_href_for(html_dir):
    rel = os.path.relpath(CSS_TARGET, start=html_dir)
    # Convert Windows backslashes to forward slashes for href
    rel = rel.replace('\\', '/')
    return rel

httrack_patterns = [
    re.compile(r'<!--[^>]*HTTrack[^>]*-->', re.IGNORECASE|re.DOTALL),
    re.compile(r'<!--\s*Mirrored from[\s\S]*?-->', re.IGNORECASE),
    re.compile(r'<!--\s*Added by HTTrack[\s\S]*?-->', re.IGNORECASE),
    re.compile(r'<!--\s*Generated by HTTrack[\s\S]*?-->', re.IGNORECASE),
]

modified = []
for dirpath, dirnames, filenames in os.walk(ROOT):
    for fn in filenames:
        if not fn.lower().endswith('.html'):
            continue
        path = os.path.join(dirpath, fn)
        try:
            with open(path, 'r', encoding='utf-8') as f:
                content = f.read()
        except UnicodeDecodeError:
            with open(path, 'r', encoding='latin-1') as f:
                content = f.read()

        orig = content
        # Remove HTTrack / Mirrored comments
        for pat in httrack_patterns:
            content = pat.sub('', content)

        # Remove any previous injected custom_theme.css links (regardless of path)
        content = re.sub(r'<link[^>]+custom_theme\.css[^>]*>\s*', '', content, flags=re.IGNORECASE)

        # Only inject if there's a </head>
        match = re.search(r'</head>', content, re.IGNORECASE)
        if match:
            html_dir = os.path.dirname(path)
            href = make_href_for(html_dir)
            inject_line = f'<link rel="stylesheet" href="{href}">'
            idx = match.start()
            content = content[:idx] + inject_line + '\n' + content[idx:]

        if content != orig:
            try:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(content)
                modified.append(path)
            except Exception as e:
                print(f'Failed to write {path}: {e}')

print(f"Modified {len(modified)} HTML files")
for p in modified:
    print(p)
