import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

# We will reference the CSS via an absolute path so hosting platforms (Render)
# reliably serve it from `/static/custom_theme.css`.
ABS_HREF = '/static/custom_theme.css'

httrack_patterns = [
    re.compile(r'<!--[^>]*HTTrack[^>]*-->', re.IGNORECASE|re.DOTALL),
    re.compile(r'<!--\s*Mirrored from[\s\S]*?-->', re.IGNORECASE),
    re.compile(r'<!--\s*Added by HTTrack[\s\S]*?-->', re.IGNORECASE),
    re.compile(r'<!--\s*Generated by HTTrack[\s\S]*?-->', re.IGNORECASE),
]

modified = []
for dirpath, dirnames, filenames in os.walk(ROOT):
    for fn in filenames:
        if not fn.lower().endswith('.html'):
            continue
        path = os.path.join(dirpath, fn)
        try:
            with open(path, 'r', encoding='utf-8') as f:
                content = f.read()
        except UnicodeDecodeError:
            with open(path, 'r', encoding='latin-1') as f:
                content = f.read()

        orig = content
        # Remove HTTrack / Mirrored comments
        for pat in httrack_patterns:
            content = pat.sub('', content)

        # Remove any previous injected custom_theme.css links (regardless of path)
        content = re.sub(r'<link[^>]+custom_theme\.css[^>]*>\s*', '', content, flags=re.IGNORECASE)

        # Inject absolute path to static CSS so all pages load the same file.
        match = re.search(r'</head>', content, re.IGNORECASE)
        if match:
            inject_line = f'<link rel="stylesheet" href="{ABS_HREF}">'
            idx = match.start()
            content = content[:idx] + inject_line + '\n' + content[idx:]

        if content != orig:
            try:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(content)
                modified.append(path)
            except Exception as e:
                print(f'Failed to write {path}: {e}')

print(f"Modified {len(modified)} HTML files")
for p in modified:
    print(p)
